### ISSUE TITLE
[Bug]dp is not sending data to pulsar

### ISSUE THREAD

**Issue by dadalongvs** [apache/inlong#5110]
### What happened

dp is not sending data to pulsar.
![image](https://user-images.githubusercontent.com/108457248/179655809-972671bd-d12d-464f-8602-d69a6b6e5d8a.png)
![image](https://user-images.githubusercontent.com/108457248/179656417-f0c452d7-4154-435a-bdee-d5a76e07c575.png)

### What you expected to happen

There is a record of data consumption in pulsar, and the last data generated in clickhouse.

### How to reproduce

When I finished the approval and kept adding data to the local source file, no data was generated in clickhouse. Finally, after finding the problem, I found that there was no data in pulsar.
![image](https://user-images.githubusercontent.com/108457248/179656037-df220ab0-32fd-4eda-a719-7f0497fa262c.png)
![image](https://user-images.githubusercontent.com/108457248/179656112-124f49ad-58e1-4a63-aced-551c331ad5c4.png)
![image](https://user-images.githubusercontent.com/108457248/179656224-2470c8cc-8498-4278-ad9c-42d1c32794d4.png)

### Environment

centos 7

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by baomingyu** [comment]
Message has been sent to dp? and  If the message has been sent to dp, please confirm whether the expected topic configuration information is contained in  conf/topics.properties,

**Comment by baomingyu** [comment]
In addition, please check whether the log contains the following information。
<img width="739" alt="image" src="https://user-images.githubusercontent.com/8108604/179679676-ace0752e-0dad-4b3f-89a1-e1b2f29c602b.png">
<img width="742" alt="image" src="https://user-images.githubusercontent.com/8108604/179680000-1a972f10-cb14-4bf7-82da-ae9b827d4ef0.png">

**Comment by dadalongvs** [comment]
@[baomingyu](https://github.com/baomingyu)
![image](https://user-images.githubusercontent.com/108457248/179680080-d2b21f41-2e9a-4a38-a1b2-18a83903e886.png)
![image](https://user-images.githubusercontent.com/108457248/179680150-8d6694c3-5f25-4564-93af-5cca4725a1bb.png)
There is this error in inlong-dataproxy/logs/.
![image](https://user-images.githubusercontent.com/108457248/179680599-db31f66f-a173-4d9b-aa37-4b90c3b16721.png)

**Comment by baomingyu** [comment]
Please check if this topic exists in the pulsar cluster. and check the initial configuration steps of the cluster. If the initial configuration information of the cluster in the Manager is incorrect, the topic may not be created in advance.

**Comment by dockerzhang** [comment]
this issue may be the same with https://github.com/apache/inlong/issues/5163, and we will look into it.

**Comment by dockerzhang** [comment]
fixed in https://github.com/apache/inlong/pull/5189. Please check again.

**Comment by dadalongvs** [comment]
When I use the latest code, I still can't get the data to pulsar, and new errors occurs.
![agent_errorlog](https://user-images.githubusercontent.com/108457248/180726156-a3050654-f47c-44d7-a4aa-ac010fdac7a0.png)
![managererrorlog](https://user-images.githubusercontent.com/108457248/180726210-0dad455b-c1d6-43f9-9de0-220beafe5e3f.png)

**Comment by ly100120** [comment]
这个问题你是否已经解决？我碰到了同样的问题，束手无策。1.4.0版本

**Comment by dockerzhang** [comment]
@ly100120 please add the steps to reproduce the issue.

**Comment by dockerzhang** [comment]
@ly100120 please try the latest code, and create a new Issue if it appears again.
